### ISSUE TITLE
error on loading plugin

### ISSUE THREAD

**Issue by aysaoif** [mrgucci1/AiChatBuddy#1]
[13:28:23 INFO]: [AiChatBuddy] Enabling AiChatBuddy v1.1
[13:28:23 ERROR]: [AiChatBuddy] API key not found in config.yml. Please configure it.
[13:28:23 INFO]: [AiChatBuddy] Disabling AiChatBuddy v1.1
[13:28:23 INFO]: [AiChatBuddy] AiChatBuddy has been disabled.
[13:28:23 ERROR]: Error occurred while enabling AiChatBuddy v1.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register AiChatBuddy v1.1 while not enabled
        at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:80) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:136) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:683) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at AiChatBuddy-1.1.jar/io.github.mrgucci1.aiChatBuddy.AiChatBuddy.onEnable(AiChatBuddy.java:53) ~[AiChatBuddy-1.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-52-e08e667]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by mrgucci1** [comment]
Hey Aysoif :) You have to add in your own Google API key, you can follow these steps (as outlined in readme)

Obtain a Google Gemini API Key: Follow the instructions at https://ai.google.dev/gemini-api/docs/api-key to obtain your API key.
Download: Get the latest AiChatBuddy.jar file from the [Releases](https://github.com/mrgucci1/AiChatBuddy/blob/master/link-to-your-releases-page) section.
Install: Place the JAR file in your Minecraft server's plugins folder.
Configure: Edit the config.yml file in the plugin's folder:
api-key: Enter your Google Gemini Pro API key.
prompt-template: (Optional) Customize the AI's prompt.
api-url: (Optional) Modify the API endpoint if needed.
bot-name: Choose the name for the AI in chat (default: "Notch").
private-questions: (Optional) Set to true for private responses (default: false).
Restart: Restart your server to enable the plugin.

**Comment by aysaoif** [comment]
actually mb, i did find the fix myself on the day i created this lmfao

but really thanks for the help of the walkthrough, ggs
